FROM --platform=linux/amd64 vision:foxy-base

ENV wd=/root/ros2_ws
ENV repo=/root/ros2_ws/src/Ros2_Yolov8

WORKDIR $wd

COPY . $repo

RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && colcon build"

# Make the entrypoint script executable
RUN chmod +x $repo/docker/entrypoint.sh

# Set the entrypoint to the script
ENTRYPOINT ["/root/ros2_ws/src/Ros2_Yolov8/docker/entrypoint.sh"]
#CMD ["ros2", "launch", "yolov8_bringup", "yolov8.launch.py", "model:=yolov8m-seg.pt"]
